language: node_js
cache:
  directories:
  - node_modules
  - "~/.npm"
node_js:
- '12'
git:
  depth: 3
script:
- yarn test
notifications:
  slack:
    secure: rtDhCK5xxLW5cIa79orr+TOO84m2+hgAK+9OqwYSzVah1It+7L7aPLYWoHooRteQSxRY6FKefGM3NCnBy/REnbrsipWhTyFbqjjJ2cghyOs1gs+giJpSD8TvXEz/4EOM/riMDFWuyxH+3jW9Rkryozu7e7wbEig7zNVhMlKrgyZxIuxII/4vLrD1vLHY3LYHv0J0v8uivGJCSpDMaYJIUberEJG7WAcpK/Ni56QUsvCmJkm/4uYFDDXQjWCs269UJLBzw4Pbtfgz39obSP25rTfjayle2yEbUdhSdauPjW5pdlPqpULoQ1BFxOQWGoIB1DMxq6wCLJuWvW/MhgAf2ZFh/fm4ovFHBJlb4bAi8JMfuatU72qihJSR35iSDPxNBr7EPbKWWqTxDM+7zHPR7KYuzG7HAm6jvFN8tuVQ7+molElOWcspsRUSd3Ml/dPoNABctbXBnfE7GUCmITzoWV0FGTIU5oQJZk9FcKKQUDR8X0h7d0s5fEmm+JUMXgXzSU9emBWaSPQEodMjCpI7o0wH3EvCMBX9vtKs2UXwV569Hw0rYY+KKHzlHpQYxJarPtgDxVGj6NMr6udVYT75wAwJSI6msQ8aQ3nsrBNxDrVrIzrLaolu8/Q71gFXbWFW+lOS4Yq7VYomSvZM18T+ruEx8TkL5Xwk4c2qlX1biPg=
  email:
    recipients:
    - ala1289@gmail.com
    - hector.olvera@ciencias.unam.mx
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  skip_cleanup: true
  keep_history: true
  api_key:
    secure: KBwbOFXjJxmsoxvt6lUKo662FBWnMdUVZRjspnEDMB1yFwtd12xwCrlI49gLybAEoEeY9M+Gvkh1iCAX+NZ+8vdNNFJlZtbREV1I2dvSVuFyDw6WaFap1qrD+GC92fnyHRas9XeYAlFGmQD/StoxO+ctlkO9+mQMDiybdARTdaPt76Gh0w7cyRoZi2dsOTxNYIV2K1Dq8ol14U3aUokEY4MdHFk/dfHC5vypowuH8SFOQgg1jhSH2BVfi9JlolHzH+IBbWsbL2lYhnriFRIdQmU3fsim6Ns3WmAPEyEItXKeGFm/FiXZ5hxiIzGx4ea94HNW0DUMD3039TehHifpI69zMm1PhyHbHvQQM/zSXR98CzfkVKCNGNnf/Lfa/xZiqgPLYn+vepuh353p5Zy1rOdZhAWtyWGibRKawhXNKyx+lfRgMooBnO8eRKMFsZLxQIyKar2qjgZEpuIgma1DcxaLJD6u0zBz1//rbnrZ88gc2mY3pmNX1Ilib2fjGlDsj+Yx/T6usD0F9Zsg2ZghU5ALVTYHjxtw+9GQR4L9iyngmYgAY3Asp6d+Elc6ehJWI/4bNBkT2TiVHVukTtIa3DzkMAPKxS0m3riPxGQDEzJxmXxgWl3XgHpG58pkRB4Z13eJLNXsL1ZWcCw66Y1sTgjb+YI6weAHRwqvrZLxfjY=
  app: halah-mentoring
  on:
    repo: hyfi06/halah-mentoring-back
